name: Update release draft

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update-release-draft:
    if: github.repository == 'NVIDIA/sphinx-llm'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      # release-drafter/release-drafter v7.3.1
      # https://github.com/release-drafter/release-drafter/releases/tag/v7.3.1
      - uses: release-drafter/release-drafter@693d20e7c1ce1a81d3a41962f85914253b518449
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
